version: 0.2

phases:
  build:
    commands:
      - echo Status Checker Has Started

      - python status_checker.py 
  post_build:
    commands:
      - echo Status Checker Build Completed
artifacts:
  files:
    - '**/*'
