version: 0.2

phases:
  install:
    commands:
      - echo Installing boto3
      - pip install -U boto3
      - echo Finished installing boto3
  build:
    commands:
      - echo Compiling status_checker.py
      - python status_checker.py
      - echo Status Checker Build Completed
      - echo SRC DIRECTORY IS $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Setting public-read permissions on artifact
      - aws s3 mv --acl public-read cfn-stack-results.md s3://tleavey-test-platform-status/cfnResults/
      - echo The cfn-stack-results have been moved successfully.
artifacts:
  files:
    - '**/*'