version: 0.2

env:
  variables:
    # Change 'tleavey-test-platform-status' to a folder name in your s3
    MY_S3_BUCKET: s3://test-platform-results/

phases:
  install:
    commands:
      - echo Installing boto3
      - pip install -U boto3
      - echo Finished installing boto3
      - sudo apt-get update
      - sudo apt-get install nodejs -y
      - sudo apt-get install npm -y
      - sudo npm install -g markdown-styles
  build:
    commands:
      - echo Going to sleep for 5 minutes.
      # - sleep 300
      - echo Just woke up.
      - echo Running status_checker.py
      - python status_checker.py
      - echo Status Checker Build Completed
      - generate-md --layout github --input statusResults.md --output index.html
      - mkdir input/
      - mv statusResults.md input/index.md
      - generate-md --layout github --input ./input --output ./output
      - google-chrome ./output/index.html
  post_build:
    commands:
      - echo Setting public-read permissions on output
      - aws s3 mv --acl public-read ./output/index.html $MY_S3_BUCKET
      - echo The results have been moved successfully.
