version: 0.2

env:
  variables:
    # Change 'test-platform-internal-projects' to a folder name in your s3
    MY_S3_BUCKET: s3://test-platform-internal-projects/

phases:
  install:
    commands:
      - echo Installing boto3
      - pip install -U boto3
      - echo Finished installing boto3
  build:
    commands:
      - echo Going to sleep for 10 minutes so all the other stacks can finish being created.
      # - sleep 600
      - sleep 10
      - echo Just woke up.
      - echo Running status_checker.py
      - python status_checker.py
      - echo Status Checker Build Completed
  post_build:
    commands:
      - echo Setting public-read permissions on output
      - aws s3 mv --acl public-read index.html $MY_S3_BUCKET
      - echo The results have been moved successfully.
