version: 0.2

phases:
  install:
    commands:
      - echo Installing boto3
      - pip install -U boto3
      - echo Finished installing boto3
  build:
    commands:
      - echo Compiling status_checker.py
      - python status_checker.py
  post_build:
    commands:
      - echo Status Checker Build Completed
      - echo Setting public-read permissions on artifact
      - aws s3 cp --acl public-read s3://tleavey-test-platform-status/cfn-stack-results.md s3://tleavey-test-platform-status/cfn-stack-results.md
artifacts:
  files:
    - cfn-stack-results.md